[workspace]
members = ["alloc"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
libc = { version = "0.2.174" }

[profile.release-with-fp]
inherits = "release"
debug = true
strip = false
debug-assertions = false
overflow-checks = false
lto = false
