[package]
name = "rts-alloc"
description = "Shared memory allocator intended for small frequent allocations"
edition = "2021"
version = "2.0.0"
license = "Apache-2.0"
repository = "https://github.com/anza-xyz/rts-alloc"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]

[target."cfg(unix)".dependencies]
libc = { version = "0.2.174" }
