[package]
name = "rts-alloc"
description = "Shared memory allocator intended for small frequent allocations"
edition = "2021"
version = "2.0.0"
license = "Apache-2.0"
repository = "https://github.com/anza-xyz/rts-alloc"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]

[target."cfg(unix)".dependencies]
libc = { version = "0.2.174" }

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Memory",
] }
